<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Mappings\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Helpers\" />
    <Folder Include="Interfaces\Infrastructure\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="UseCases\Actividades\" />
    <Folder Include="UseCases\ToDos\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM_MDaSoporteTI.Domain\CRM_MDaSoporteTI.Domain.csproj" />
    <ProjectReference Include="..\CRM_MDaSoporteTI.Infrastructure\CRM_MDaSoporteTI.Infrastructure.csproj" />
    <ProjectReference Include="..\CRM_MDaSoporteTI.Shared\CRM_MDaSoporteTI.Shared.csproj" />
  </ItemGroup>

</Project>
