<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a6839600-b595-4b46-999a-7cd918490682</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM_MDaSoporteTI.Application\CRM_MDaSoporteTI.Application.csproj" />
    <ProjectReference Include="..\CRM_MDaSoporteTI.Infrastructure\CRM_MDaSoporteTI.Infrastructure.csproj" />
    <ProjectReference Include="..\CRM_MDaSoporteTI.Shared\CRM_MDaSoporteTI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>

</Project>
